#!/bin/bash

export CUDA_VISIBLE_DEVICES=0
python llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --model_name_or_path liuhaotian/llava-v1.5-7b \
    --version v1 \
    --data_path ../../all_data/EgocentricDataset/additional_data/imagenet_QA_7b_clean_test.json \
    --valid_data_path ../../all_data/EgocentricDataset/additional_data/benchmark_mini.json \
    --mock_data_path ../../all_data/EgocentricDataset/additional_data/imagenet_QA_7b_clean_test.json \
    --image_folder ../../all_data/EgocentricDataset/imagenet_after  \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --unfreeze_encoder False \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-7b-task-lora \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "epoch" \
    --eval_steps 30 \
    --save_strategy "epoch" \
    --save_steps 120 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 1 \
    --lazy_preprocess True \
    --report_to wandb \
    --run_name "Fifth Try" \
    --seed 0